version: '3.8'

services:
  andes-tech:
    container_name: andes-tech
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 andes/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/andes-tech
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.12
    container_name: redis-server
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    container_name: celery-worker
    command: celery -A andes.andes worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/andes-tech
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: .
    container_name: celery-beat
    command: celery -A andes.andes beat --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/andes-tech
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
    # external: true # Descomenta esto si tienes un volumen externo ya creado
