# Generated by Django 4.2.15 on 2025-08-10 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasMedidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoMedidor', models.CharField(blank=True, max_length=45, null=True, verbose_name='TipoMedidor')),
                ('CapacidadMaximaKg', models.SmallIntegerField(blank=True, null=True, verbose_name='CapacidadMaximaKg')),
                ('PesoActualCilindroKg', models.SmallIntegerField(blank=True, null=True, verbose_name='PesoActualCilindroKg')),
                ('PresionMaximaPSI', models.SmallIntegerField(blank=True, null=True, verbose_name='PresionMaximaPSI')),
                ('CaracteristicasMedidorcol', models.CharField(blank=True, max_length=45, null=True, verbose_name='CaracterísticasMedidorcol')),
            ],
            options={
                'db_table': 'CaracterísticasMedidor',
            },
        ),
        migrations.CreateModel(
            name='NivelImportancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=45, null=True, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'NivelImportancia',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_notificacion', models.CharField(blank=True, max_length=45, null=True, verbose_name='nombre_notificacion')),
                ('estado', models.BooleanField(blank=True, null=True, verbose_name='estado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='TipoPeticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True, verbose_name='nombre')),
            ],
            options={
                'db_table': 'TipoPeticion',
            },
        ),
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='nombreTipoSensor')),
            ],
            options={
                'db_table': 'tipoSensor',
            },
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaActualizacion', models.DateTimeField(blank=True, null=True, verbose_name='fechaActualizacion')),
                ('presion', models.SmallIntegerField(blank=True, null=True, verbose_name='presion')),
                ('temperatura', models.SmallIntegerField(blank=True, null=True, verbose_name='temperatura')),
                ('densidad', models.SmallIntegerField(blank=True, null=True, verbose_name='densidad')),
                ('cantidad_actual_gas', models.SmallIntegerField(blank=True, null=True, verbose_name='cantidad_actual_gas')),
                ('cantidad_actual_porcentaje', models.SmallIntegerField(blank=True, null=True, verbose_name='cantidad_actual_porcentaje')),
                ('caudal', models.SmallIntegerField(blank=True, null=True, verbose_name='caudal')),
                ('caracteristicas_medidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.caracteristicasmedidor', verbose_name='CaracterísticasMedidor')),
            ],
            options={
                'db_table': 'Variables',
            },
        ),
        migrations.CreateModel(
            name='TcketSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(blank=True, max_length=100, null=True, verbose_name='asunto')),
                ('estado', models.BinaryField(blank=True, null=True, verbose_name='estado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha_creacion')),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha_actualizacion')),
                ('archivos_comprimidos', models.BinaryField(blank=True, null=True, verbose_name='archivos_comprimidos')),
                ('NivelImportancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interface.nivelimportancia', verbose_name='NivelImportancia')),
                ('TipoPeticion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interface.tipopeticion', verbose_name='TipoPeticion')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='empresa')),
            ],
            options={
                'db_table': 'TcketSoporte',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True, verbose_name='nombre')),
                ('imei', models.CharField(blank=True, max_length=45, null=True, verbose_name='imei')),
                ('numSerial', models.CharField(blank=True, max_length=45, null=True, verbose_name='numSerial')),
                ('estado', models.BinaryField(blank=True, null=True, verbose_name='estado')),
                ('localizacion', models.CharField(blank=True, max_length=45, null=True, verbose_name='localizacion')),
                ('bateria', models.SmallIntegerField(blank=True, null=True, verbose_name='bateria')),
                ('senal', models.CharField(blank=True, max_length=45, null=True, verbose_name='señal')),
                ('ultimaActualizacion', models.DateTimeField(blank=True, null=True, verbose_name='ultimaActualizacion')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='empresa')),
                ('tipoSensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interface.tiposensor', verbose_name='tipoSensor')),
            ],
            options={
                'db_table': 'Sensor',
            },
        ),
        migrations.AddField(
            model_name='caracteristicasmedidor',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.sensor', verbose_name='Sensor'),
        ),
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAlarma', models.CharField(blank=True, max_length=45, null=True, verbose_name='nombreAlarma')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='fecha')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('estado', models.BooleanField(blank=True, null=True, verbose_name='estado')),
                ('Sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.sensor', verbose_name='Sensor')),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.notificacion', verbose_name='notificacion')),
            ],
            options={
                'db_table': 'alarma',
            },
        ),
    ]
