# Generated by Django 4.2.15 on 2025-06-09 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sen_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id of sensor')),
                ('sen_name', models.CharField(max_length=85, verbose_name='name of sensor')),
                ('sen_direction', models.CharField(max_length=45, verbose_name='type of sensor')),
                ('max_output_force', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='pressure force in max volume')),
                ('max_masa', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='maximun masa allowed in kg')),
                ('sen_serialno', models.CharField(max_length=45, verbose_name='serial of sensor')),
                ('sen_imei', models.CharField(max_length=45, null=True, verbose_name='imei of sensor')),
            ],
            options={
                'db_table': 'andes_sensors',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_name', models.CharField(max_length=75, verbose_name='name of user')),
                ('us_contact', models.CharField(max_length=15, verbose_name='contact of user')),
                ('us_mail', models.EmailField(max_length=95, verbose_name='mail of user')),
                ('us_hash_pass', models.TextField(verbose_name='password of user')),
                ('us_status', models.BinaryField(default=b'\x01', verbose_name='status of user')),
            ],
            options={
                'db_table': 'andes_users',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='temperature')),
                ('var_radiofrecuency', models.IntegerField(verbose_name='signal')),
                ('var_presure', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='current output of gas')),
                ('var_time', models.DateTimeField(verbose_name='current time')),
                ('var_output_capacity', models.IntegerField(null=True, verbose_name='current output force')),
                ('var_current_capacity', models.IntegerField(null=True, verbose_name='current percentage of gas')),
                ('var_litres', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='current amount of litres')),
                ('var_battery', models.IntegerField(verbose_name='current percentage battery')),
                ('localizacion', models.CharField(max_length=45, null=True, verbose_name='current location')),
                ('sensors_sen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.sensor')),
            ],
            options={
                'db_table': 'andes_variables',
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='user_us_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.user'),
        ),
    ]
