# Generated by Django 4.2.15 on 2025-09-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcketsoporte',
            name='NivelImportancia',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', verbose_name='NivelImportancia'),
        ),
        migrations.DeleteModel(
            name='NivelImportancia',
        ),
    ]
