# Generated by Django 4.2.15 on 2025-09-30 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_alter_tcketsoporte_nivelimportancia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasCilindro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True, verbose_name='nombre')),
                ('volumen_interno_m3', models.FloatField(blank=True, null=True, verbose_name='volumen interno (m3)')),
                ('masa_cil_vacio_kg', models.FloatField(blank=True, null=True, verbose_name='masa cilindro al vacío (Kg)')),
                ('masa_cil_lleno_kg', models.FloatField(blank=True, null=True, verbose_name='masa cilindro lleno (Kg')),
                ('masa_gas_restant_kg', models.FloatField(blank=True, null=True, verbose_name='cant. gas restante (Kg')),
                ('coef_descarga_cd', models.FloatField(blank=True, null=True, verbose_name='coeficiente de descarga (cd)')),
                ('diametro_orificio_m', models.FloatField(blank=True, null=True, verbose_name='diametro de orificio (m')),
                ('notas', models.CharField(blank=True, max_length=45, null=True, verbose_name='notas')),
            ],
            options={
                'db_table': 'CaracteristicasCilindro',
            },
        ),
        migrations.CreateModel(
            name='ComposicionGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion')),
                ('masa_molar', models.FloatField(blank=True, null=True, verbose_name='masa molar')),
                ('y_entropia', models.FloatField(blank=True, null=True, verbose_name='y entropia')),
                ('z_factor', models.FloatField(blank=True, null=True, verbose_name='z factor')),
                ('densidad', models.FloatField(blank=True, null=True, verbose_name='densidad')),
            ],
            options={
                'db_table': 'ComposicionGas',
            },
        ),
        migrations.CreateModel(
            name='GasRestante',
            fields=[
                ('Sensor_idSensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='interface.sensor', verbose_name='Sensor_idSensor')),
                ('localizacion', models.CharField(blank=True, max_length=45, null=True, verbose_name='localizacion')),
                ('bateria', models.CharField(blank=True, max_length=45, null=True, verbose_name='bateria')),
                ('server_deviceNo', models.CharField(blank=True, max_length=85, null=True, verbose_name='server deviceNo')),
            ],
            options={
                'db_table': 'GasRestante',
            },
        ),
        migrations.CreateModel(
            name='ResultsGasRestante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='última actualización')),
                ('presion_gauge_pa', models.FloatField(blank=True, null=True, verbose_name='presión manómetro (Pa)')),
                ('presion_abs_pa', models.FloatField(blank=True, null=True, verbose_name='presión abs. (Pa)')),
                ('temperature_k', models.FloatField(blank=True, null=True, verbose_name='temperatura (k)')),
                ('estado_fase', models.CharField(blank=True, choices=[('bifasico', 'bifásico'), ('vapor', 'solo vapor'), ('descon.', 'desconocido')], default='bifasico', max_length=20, null=True, verbose_name='estado de fase del gas')),
                ('caudal_masa_kg_s', models.FloatField(blank=True, null=True, verbose_name='caudal de masa (Kg/s)')),
                ('masa_remov_kg', models.FloatField(blank=True, null=True, verbose_name='masa de gas removida (Kg)')),
                ('masa_restante_kg', models.FloatField(blank=True, null=True, verbose_name='masa de gas restante (Kg)')),
                ('moles_restantes_kg', models.FloatField(blank=True, null=True, verbose_name='cant. de moles restantes (Kg)')),
                ('metodo_calculo', models.CharField(blank=True, max_length=45, null=True, verbose_name='método del cálculo')),
                ('masa_balanza_kg', models.FloatField(blank=True, null=True, verbose_name='nuevo peso de la balanza (Kg)')),
                ('valido', models.SmallIntegerField(blank=True, null=True, verbose_name='cálculos válidos')),
                ('CaracterísticasCilindro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.caracteristicascilindro', verbose_name='Cilindro a monitorear')),
            ],
            options={
                'db_table': 'ResultsGasRestante',
            },
        ),
        migrations.CreateModel(
            name='ServerCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True, verbose_name='nombre')),
                ('server_userId', models.CharField(blank=True, max_length=10, null=True, verbose_name='server_userId')),
                ('server_clientId', models.CharField(blank=True, max_length=45, null=True, verbose_name='server_clientId')),
                ('server_access_token', models.CharField(blank=True, max_length=85, null=True, verbose_name='server_access_token')),
                ('token_updated', models.DateTimeField(blank=True, null=True, verbose_name='token_updated')),
            ],
            options={
                'db_table': 'server_credentials',
            },
        ),
        migrations.RemoveField(
            model_name='variables',
            name='caracteristicas_medidor',
        ),
        migrations.RemoveField(
            model_name='alarma',
            name='notificacion',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='bateria',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='localizacion',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='numSerial',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='senal',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='ultimaActualizacion',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='alarma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.alarma', verbose_name='alarma'),
        ),
        migrations.AddField(
            model_name='tiposensor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='alarma',
            name='Sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.sensor', verbose_name='sensor'),
        ),
        migrations.AlterField(
            model_name='alarma',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='alarma',
            name='estado',
            field=models.BooleanField(blank=True, null=True, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='alarma',
            name='nombreAlarma',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='nombre alarma'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='estado',
            field=models.BooleanField(blank=True, null=True, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='nombre_notificacion',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='nombre de notificacion'),
        ),
        migrations.DeleteModel(
            name='CaracteristicasMedidor',
        ),
        migrations.DeleteModel(
            name='Variables',
        ),
        migrations.AddField(
            model_name='gasrestante',
            name='server_credentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.servercredentials', verbose_name='credenciales del servidor'),
        ),
        migrations.AddField(
            model_name='caracteristicascilindro',
            name='ComposicionGas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interface.composiciongas', verbose_name='Composición del gas'),
        ),
        migrations.AddField(
            model_name='caracteristicascilindro',
            name='GasRestante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.gasrestante', verbose_name='sensor de gas restante'),
        ),
    ]
