# Generated by Django 4.2.15 on 2025-09-30 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interface', '0003_caracteristicascilindro_composiciongas_gasrestante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensajes', models.TextField(blank=True, null=True, verbose_name='mensaje')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='timestamp')),
                ('TcketSoporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.tcketsoporte', verbose_name='ticket soporte')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'db_table': 'mensajes',
            },
        ),
    ]
