# Generated by Django 4.2.15 on 2025-10-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='servercredentials',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion'),
        ),
    ]
