# Generated by Django 4.2.15 on 2025-10-02 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_servercredentials_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicascilindro',
            name='ComposicionGas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interface.composiciongas', verbose_name='Composición del gas'),
        ),
        migrations.AlterField(
            model_name='caracteristicascilindro',
            name='GasRestante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interface.gasrestante', verbose_name='sensor de gas restante'),
        ),
    ]
