# Generated by Django 4.2.15 on 2025-10-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_alter_caracteristicascilindro_composiciongas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servercredentials',
            name='authorization',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='autorización'),
        ),
        migrations.AddField(
            model_name='servercredentials',
            name='password',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='contraseña'),
        ),
        migrations.AddField(
            model_name='servercredentials',
            name='user',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='usuario'),
        ),
    ]
