# Generated by Django 4.2.15 on 2025-10-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_servercredentials_authorization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servercredentials',
            name='authorization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='autorización'),
        ),
    ]
