# Generated by Django 4.2.15 on 2025-10-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_alter_servercredentials_authorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicascilindro',
            name='porc_masa_gas_restant',
            field=models.FloatField(blank=True, null=True, verbose_name='porc. masa gas restante (%)'),
        ),
        migrations.AlterField(
            model_name='servercredentials',
            name='server_access_token',
            field=models.CharField(blank=True, max_length=85, null=True, verbose_name='token de acceso'),
        ),
        migrations.AlterField(
            model_name='servercredentials',
            name='server_clientId',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='id unico de cliente en el servidor'),
        ),
        migrations.AlterField(
            model_name='servercredentials',
            name='server_userId',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='id de user en el servidor'),
        ),
        migrations.AlterField(
            model_name='servercredentials',
            name='token_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ultima actualización del token'),
        ),
    ]
