# Generated by Django 4.2.15 on 2025-10-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_caracteristicascilindro_porc_masa_gas_restant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristicascilindro',
            name='porc_masa_gas_restant',
        ),
        migrations.AddField(
            model_name='resultsgasrestante',
            name='porc_masa_gas_restant',
            field=models.FloatField(blank=True, null=True, verbose_name='porc. masa gas restante (%)'),
        ),
    ]
