# Generated by Django 4.2.15 on 2025-10-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_remove_caracteristicascilindro_porc_masa_gas_restant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasrestante',
            name='toleranciaMins',
            field=models.IntegerField(blank=True, null=True, verbose_name='tolerancia de tiempo en mins'),
        ),
    ]
