# Generated by Django 4.2.15 on 2025-10-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0011_gasrestante_toleranciamins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsgasrestante',
            name='estado_fase',
            field=models.CharField(blank=True, choices=[(None, 'Ninguno'), ('choked', 'Ahogado'), ('no_choked', 'No ahogado')], default='None', max_length=20, null=True, verbose_name='estado de fase del gas'),
        ),
    ]
