# Generated by Django 4.2.15 on 2025-10-14 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_alter_resultsgasrestante_estado_fase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultsgasrestante',
            old_name='CaracterísticasCilindro',
            new_name='CaracteristicasCilindro',
        ),
    ]
