# Generated by Django 4.2.15 on 2025-10-14 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0013_rename_característicascilindro_resultsgasrestante_caracteristicascilindro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultsgasrestante',
            old_name='CaracteristicasCilindro',
            new_name='caracteristicas_cilindro',
        ),
    ]
