# Generated by Django 4.2.15 on 2025-10-14 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_area_operador_cargo'),
        ('interface', '0014_rename_caracteristicascilindro_resultsgasrestante_caracteristicas_cilindro'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsgasrestante',
            name='porc_masa_gas_extracted',
            field=models.FloatField(blank=True, null=True, verbose_name='porc. masa gas utilizada (%)'),
        ),
        migrations.AlterField(
            model_name='gasrestante',
            name='bateria',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='batería restante'),
        ),
        migrations.AlterField(
            model_name='gasrestante',
            name='localizacion',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='localización del sensor'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='hora y fecha del comentario'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='empresa del sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='estado',
            field=models.BinaryField(blank=True, null=True, verbose_name='estado del sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='nombre',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='nombre del sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipoSensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interface.tiposensor', verbose_name='tipo del sensor'),
        ),
        migrations.AlterField(
            model_name='tcketsoporte',
            name='NivelImportancia',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', verbose_name='Nivel de importancia'),
        ),
        migrations.AlterField(
            model_name='tcketsoporte',
            name='TipoPeticion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interface.tipopeticion', verbose_name='Tipo de peticion'),
        ),
        migrations.AlterField(
            model_name='tcketsoporte',
            name='archivos_comprimidos',
            field=models.BinaryField(blank=True, null=True, verbose_name='archivos comprimidos'),
        ),
        migrations.AlterField(
            model_name='tcketsoporte',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='tcketsoporte',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa', verbose_name='mensaje de la empresa'),
        ),
        migrations.AlterField(
            model_name='tcketsoporte',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de actualizacion'),
        ),
        migrations.AlterField(
            model_name='tcketsoporte',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='tiposensor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='descripción del tipo de sensor'),
        ),
        migrations.AlterField(
            model_name='tiposensor',
            name='nombre',
            field=models.CharField(max_length=45, verbose_name='nombre del tipo de sensor'),
        ),
    ]
