# Generated by Django 4.2.15 on 2025-10-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_resultsgasrestante_porc_masa_gas_extracted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
