services:
  andes-tech:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate --no-input && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
