# Generated by Django 4.2.15 on 2024-08-09 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sen_id', models.AutoField(primary_key=True, serialize=False)),
                ('sen_name', models.CharField(max_length=85)),
                ('sen_type', models.CharField(max_length=45)),
                ('max_capacity', models.IntegerField()),
                ('sen_serialno', models.CharField(max_length=45)),
                ('sen_imei', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'andes_sensors',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_name', models.CharField(max_length=75)),
                ('us_contact', models.CharField(max_length=15)),
                ('us_mail', models.EmailField(max_length=95)),
                ('us_hash_pass', models.TextField()),
                ('us_status', models.BinaryField(default=b'\x01')),
            ],
            options={
                'db_table': 'andes_users',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('var_radiofrecuency', models.IntegerField()),
                ('var_presure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('var_time', models.DateTimeField()),
                ('var_capacity', models.IntegerField()),
                ('var_battery', models.IntegerField()),
                ('localizacion', models.TextField()),
                ('sensors_sen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sensor')),
            ],
            options={
                'db_table': 'andes_variables',
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='user_us_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
    ]
