# Generated by Django 4.2.15 on 2024-08-09 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85)),
                ('type', models.CharField(max_length=45)),
                ('max_capacity', models.IntegerField()),
                ('serial_number', models.CharField(max_length=45)),
                ('imei', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=95)),
                ('password_hash', models.TextField()),
                ('status', models.BinaryField(default=b'\x01')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('radiofrequency', models.IntegerField()),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dateTime', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('location', models.TextField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
    ]
