# Generated by Django 4.2.15 on 2024-08-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='var_capacity',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sen_porc_cap',
            field=models.IntegerField(null=True, verbose_name='current percetage of capacity'),
        ),
        migrations.AddField(
            model_name='variable',
            name='var_current_capacity',
            field=models.IntegerField(null=True, verbose_name='current percentage of gas'),
        ),
        migrations.AddField(
            model_name='variable',
            name='var_output_capacity',
            field=models.IntegerField(null=True, verbose_name='current output force'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='max_capacity',
            field=models.IntegerField(verbose_name='percentage of output force'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sen_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id of sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sen_imei',
            field=models.CharField(max_length=45, null=True, verbose_name='imei of sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sen_name',
            field=models.CharField(max_length=85, verbose_name='name of sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sen_serialno',
            field=models.CharField(max_length=45, verbose_name='serial of sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sen_type',
            field=models.CharField(max_length=45, verbose_name='type of sensor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='us_contact',
            field=models.CharField(max_length=15, verbose_name='contact of user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='us_hash_pass',
            field=models.TextField(verbose_name='password of user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='us_mail',
            field=models.EmailField(max_length=95, verbose_name='mail of user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='us_name',
            field=models.CharField(max_length=75, verbose_name='name of user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='us_status',
            field=models.BinaryField(default=b'\x01', verbose_name='status of user'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='localizacion',
            field=models.CharField(max_length=45, null=True, verbose_name='current location'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='var_battery',
            field=models.IntegerField(verbose_name='current percentage battery'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='var_presure',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='current output of gas'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='var_radiofrecuency',
            field=models.IntegerField(verbose_name='signal'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='var_temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='temperature'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='var_time',
            field=models.DateTimeField(verbose_name='current time'),
        ),
    ]
