# Generated by Django 4.2.15 on 2024-08-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_variable_var_capacity_sensor_sen_porc_cap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='max_capacity',
            new_name='max_output_force',
        ),
        migrations.AddField(
            model_name='sensor',
            name='max_masa',
            field=models.IntegerField(null=True, verbose_name='maximun masa allowed in kg'),
        ),
    ]
