# Generated by Django 4.2.15 on 2024-08-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_max_capacity_sensor_max_output_force_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sen_porc_cap',
        ),
    ]
