# Generated by Django 4.2.15 on 2024-09-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_sensor_sen_porc_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='var_litres',
            field=models.IntegerField(null=True, verbose_name='current amount of litres'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='max_output_force',
            field=models.IntegerField(verbose_name='maximum pressure force in psi'),
        ),
    ]
