# Generated by Django 4.2.15 on 2024-09-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_variable_var_litres_alter_sensor_max_output_force'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='var_litres',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='current amount of litres'),
        ),
    ]
