# Generated by Django 4.2.15 on 2024-09-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_variable_var_litres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='max_masa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='maximun masa allowed in kg'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='max_output_force',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='pressure force in max volume'),
        ),
    ]
