# Generated by Django 4.2.15 on 2024-09-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_sensor_max_masa_alter_sensor_max_output_force'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='var_litres',
        ),
        migrations.AddField(
            model_name='variable',
            name='var_grams',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='current amount of grams'),
        ),
    ]
