# Generated by Django 4.2.15 on 2024-10-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_variable_var_litres_variable_var_grams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='sen_type',
            new_name='sen_direction',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='var_grams',
        ),
        migrations.AddField(
            model_name='variable',
            name='var_litres',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='current amount of litres'),
        ),
    ]
