# Generated by Django 4.2.15 on 2025-06-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_sen_type_sensor_sen_direction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='variable',
            options={'managed': False},
        ),
    ]
