# Generated by Django 4.2.15 on 2025-06-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_sensor_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='sensors_sen_id',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Variable',
        ),
    ]
