# Generated by Django 4.2.15 on 2025-08-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='tipoPersona',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='tipo de persona'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombreDoc',
            field=models.CharField(max_length=45, verbose_name='tipo de documento'),
        ),
    ]
