# Generated by Django 4.2.15 on 2025-08-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tipodocumento_tipopersona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='estado'),
        ),
    ]
