# Generated by Django 4.2.15 on 2025-08-25 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usuario_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operador',
            old_name='area',
            new_name='cargo',
        ),
    ]
